name: Create Manifests
description: Creates the manifests for the images
inputs:
  version:
    description: The version the manifests are for
    required: true
  registry:
    description: The registry where the manifests are pushed
    required: true
  repository:
    description: The repository in the registry where the manifests are pushed
    required: true
  combined:
    description: Should it create a combined manifests for amd64 and arm64 builds
    required: true
  repository-username:
    description: The username to access the registry/repository
    required: true
  repository-password:
    description: The password to access the registry/repository
    required: true
runs:
  using: "composite"
  steps:
    - name: Login to Registry
      uses:  docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b # v2
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.repository-username }}
        password: ${{ inputs.repository-password }}
    - name: Create manifest
      env:
        IMAGE: ${{ inputs.registry }}/${{ inputs.repository }}
      shell: bash
      run: |
        hack/build/ci/create-manifest.sh "${IMAGE}" "${{ inputs.version }}" ${{ inputs.combined }}
