name: Sign Image
description: Signs the operator docker image
inputs:
  image:
    description: The full image tag that will be signed
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Cosign
      uses: sigstore/cosign-installer@b3413d484cc23cf8778c3d2aa361568d4eb54679 # v2.5.1
    - name: Sign image with a key
      shell: bash
      run: |
        cosign sign --key env://COSIGN_PRIVATE_KEY ${TAGS}
      env:
        TAGS: ${{ steps.prepare_tags.outputs.tags }}
        COSIGN_PRIVATE_KEY: ${{secrets.COSIGN_PRIVATE_KEY}}
        COSIGN_PASSWORD: ${{secrets.COSIGN_PASSWORD}}
    - name: Sign the images with GitHub OIDC Token
      shell: bash
      run: cosign sign ${TAGS}
      env:
        TAGS: ${{ steps.prepare_tags.outputs.tags }}
        COSIGN_EXPERIMENTAL: "true"