---
# Source: dynatrace-operator/templates/Common/kubernetes-monitoring/clusterrole-kubernetes-monitoring.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dynatrace-kubernetes-monitoring
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - pods
      - namespaces
      - replicationcontrollers
      - events
      - resourcequotas
      - pods/proxy
      - nodes/proxy
      - services
    verbs:
      - list
      - watch
      - get
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - list
      - watch
      - get
  - apiGroups:
      - apps
    resources:
      - deployments
      - replicasets
      - statefulsets
      - daemonsets
    verbs:
      - list
      - watch
      - get
  - apiGroups:
      - apps.openshift.io
    resources:
      - deploymentconfigs
    verbs:
      - list
      - watch
      - get
  - apiGroups:
      - config.openshift.io
    resources:
      - clusterversions
    verbs:
      - list
      - watch
      - get
  - nonResourceURLs:
      - /metrics
      - /version
      - /readyz
      - /livez
    verbs:
      - get
---
# Source: dynatrace-operator/templates/Common/kubernetes-monitoring/clusterrolebinding-kubernetes-monitoring.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dynatrace-kubernetes-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dynatrace-kubernetes-monitoring
subjects:
  - kind: ServiceAccount
    name: dynatrace-kubernetes-monitoring
    namespace: dynatrace
