name: Publish images

on:
  push:
    branches:
      - "release-*"
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  prepare:
    name: Prepare properties
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare build parameters
        id: prep
        run: |
          hack/build/ci/prepare-build-variables.sh
    outputs:
      labels: ${{ steps.prep.outputs.docker_image_labels }}
      version: test
      goargs: ${{ steps.prep.outputs.go_build_args }}
      goversion: ${{ steps.prepenv.outputs.goversion }}

  # Workflow needs to build docker images again as separate workflows don't have access to others artifacts
  # https://github.com/actions/download-artifact/issues/3
  build:
    name: Build images
    uses: ./.github/workflows/build-dockerimage.yaml
    needs: [prepare]
    with:
      platform: amd64
      goversion: ${{ needs.prepare.outputs.goversion }}
      goargs: ${{ needs.prepare.outputs.goargs }}
      labels: ${{ needs.prepare.outputs.labels }}
      image-tag: ${{ needs.prepare.outputs.version }}

  push:
    name: Push images
    uses: ./.github/workflows/upload-dockerimage.yaml
    needs: [build]
    with:
      platform: amd64
      labels: ${{ needs.prepare.outputs.labels }}
      version: test
      registry: quay.io
      repository: dynatrace/dynatrace-operator
    secrets:
      docker_repo_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_repo_password: ${{ secrets.DOCKERHUB_PASSWORD }}

            

  # manifest:
  #   name: Create manifests
  #   needs: [prepare, push]
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       registry: [ rhcc, gcr, dockerhub ]
  #       include:
  #         - registry: rhcc
  #           url: quay.io
  #           repository: dynatrace/dynatrace-operator
  #           username: ${{ secrets.DOCKERHUB_USERNAME }}
  #           password: ${{ secrets.DOCKERHUB_PASSWORD }}
  #         - registry: gcr
  #           url: quay.io
  #           repository: dynatrace/dynatrace-operator
  #           username: ${{ secrets.DOCKERHUB_USERNAME }}
  #           password: ${{ secrets.DOCKERHUB_PASSWORD }}
  #         - registry: dockerhub
  #           url: quay.io
  #           repository: dynatrace/dynatrace-operator
  #           username: ${{ secrets.DOCKERHUB_USERNAME }}
  #           password: ${{ secrets.DOCKERHUB_PASSWORD }}
  #   steps:
  #     - name: Login to ${{matrix.repository}}
  #       uses: docker/login-action@v1
  #       with:
  #         registry: ${{ matrix.url }}
  #         username: ${{ matrix.username }}
  #         password: ${{ matrix.password }}
  #     - name: Create manifest for ${{matrix.repository}}
  #       env:
  #         IMAGE: ${{matrix.url}}/${{matrix.repository}}
  #       # Simply pulls, otherwise the artifact would need to be re-downloaded and re-tagged correctly which would mean
  #       # two more steps instead of two more lines
  #       run: |          
  #         docker pull ${{matrix.url}}/${{matrix.repository}}:${{ needs.prepare.outputs.version }}-${{ matrix.registry }}-amd64
  #         docker pull ${{matrix.url}}/${{matrix.repository}}:${{ needs.prepare.outputs.version }}-${{ matrix.registry }}-arm64
  #         hack/build/ci/create-manifest.sh "${IMAGE}" "${{ needs.prepare.outputs.version }}" true
